### ISSUE TITLE
No favico

### ISSUE THREAD

**Issue by afmsavage** [Ricochet-Exchange/ricochet-exchange.github.io#11]
There's no favico on the site.  I have 50 tabs open and im like yo i need to check my ricochet tab, and I can't find it in the sea of tabs since it doesn't have its icon there.  
<img width="150" alt="image" src="https://user-images.githubusercontent.com/29739267/154739571-7ee861dd-40fb-454f-80eb-d4b26f8d0374.png">

**Comment by akashprasher** [comment]
Added!
