### ISSUE TITLE
Small Tweak Batch

### ISSUE THREAD

**Issue by joeljesu** [Ricochet-Exchange/ricochet-exchange.github.io#7]
1. Space the top of the gif down such that it aligns with the red line

![image](https://user-images.githubusercontent.com/62968241/153457112-97af99bb-7e31-4bd8-945a-5f98ed4b7ad9.png)

The challenge here is that the spacing on the mobile layout looks perfect and shouldn't be modified by this downward push.

2. I would like to see this entire section fitted into a single view. This screenshot is from a standard 13'' laptop view and the top and the bottom are cut off. 

![image](https://user-images.githubusercontent.com/62968241/153458558-e7d2fb70-ea0e-4d5f-a954-a07349968bd6.png)

3. Switch the font to the DM Sans font used in this Google Slides template: https://docs.google.com/presentation/d/1mECbmduX1imFWKdycgq5_T26_c3PNL05Yr1YukUsvwA/edit#slide=id.p

Google Fonts link: https://fonts.google.com/specimen/DM+Sans?query=dm+sans

**Comment by fkinzerskyi** [comment]
I could pick it up)
